model:
  model_type: "lvm_med"
  ann_type: "label"
  dataset: "DAVIS"
  ensemble_size: 5
  gpus: "cuda:0"
  in_chns: 3
  base_original_checkpoint: "imagenet_v2"
  val_epoch: 5
policy:
  policy_type: ranked
  seed: 1
  resume: True
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  dataset_type: "DAVIS"
  data_geometry_type: kcenter_greedy
  seed: 1
  contrastive: True
  feature_model: True
  feature_model_params:
    in_chns: 3
    encoder: resnet18
    batch_size: 8
    seed: 1
    use_slice_pos: True
    use_phase: True
    pos_loss1: True
    pos_loss1_wt: .3
    pos_loss1_mask:
      - 2
    pos_loss2: True
    pos_loss2_wt: .1
    reset_sampler_every_epoch: True
exp_dir: "LVMMED_imagenet_sup_DAVIS_exp1_coreset_pos_loss1_wt03_pos_loss2_wt01_use_slice_pos_use_phase_v19"