model:
  model_type: "strong_3d"
  ann_type: "label"
  ensemble_size: 5
  batch_size: 1
  gpus: "cuda:0"
policy:
  policy_type: random
  seed: 1
  ensemble_kwargs:
    skip: False
    inf_test: False
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
exp_dir: "DMPLS_3D_exp1_random_v18"