model:
  model_type: "lvm_med"
  ann_type: "label"
  dataset: "CHAOS_CT"
  ensemble_size: 5
  gpus: "cuda:0"
  base_original_checkpoint: "lvm-med-resnet"
  val_epoch: 5
policy:
  policy_type: ranked
  seed: 1
  resume: True
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  dataset_type: "CHAOS_CT"
  data_geometry_type: kcenter_greedy
  seed: 1
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    seed: 1
    use_phase: True
    pos_loss1: True
    pos_loss1_wt: .35
    reset_sampler_every_epoch: True
exp_dir: "LVMMED_sup_CHAOS_exp1_coreset_pos_loss1_wt035_use_phase_v17"