model:
  model_type: "lvm_med"
  ann_type: "label"
  ensemble_size: 5
  gpus: "cuda:0"
  base_original_checkpoint: "lvm-med-resnet"
  val_epoch: 5
policy:
  policy_type: ranked
  seed: 3
  resume: True
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  seed: 3
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    seed: 3
    loss_wt: 0.0
    use_slice_pos: False
    use_phase: True
    use_patient: True
    pos_loss1: True
    pos_loss1_wt: .125
    pos_loss1_mask:
      - 2
    pos_loss2: True
    pos_loss2_wt: .875
    reset_sampler_every_epoch: True
exp_dir: "LVMMED_sup_exp3_coreset_xt0_pos_loss1_wt0125_pos_loss2_wt0875_use_phase_use_patient_v19"