model:
  model_type: "lvm_med"
  ann_type: "label"
  ensemble_size: 5
  gpus: "cuda:0"
  base_original_checkpoint: "lvm-med-resnet"
  val_epoch: 5
policy:
  policy_type: ranked
  seed: 4
  resume: True
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  seed: 4
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    seed: 4
    loss_wt: 1.0
    reset_sampler_every_epoch: True
exp_dir: "LVMMED_sup_exp4_coreset_xt1_v19"