model:
  model_type: "lvm_med"
  ann_type: "label"
  ensemble_size: 5
  gpus: "cuda:0"
  base_original_checkpoint: "scratch"
  val_epoch: 5
policy:
  policy_type: ranked
  seed: 1
  resume: True
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  seed: 1
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 9
    seed: 1
    use_phase: True
    use_patient: True
    pos_loss1: True
    pos_loss1_wt: .35
    pos_loss1_mask:
      - 2
    pos_loss2: True
    pos_loss2_wt: .05
    reset_sampler_every_epoch: True
exp_dir: "LVMMED_scratch_sup_exp1_coreset_pos_loss1_wt035_pos_loss2_wt005_use_phase_use_patient_v18"