model:
  model_type: "lvm_med"
  ann_type: "label"
  ensemble_size: 5
  gpus: "cuda:0"
  encoder_name: "resnet18"
  base_original_checkpoint: /local2/amvepa91/al-seg1/DMPLS_exp1_coreset_pos_wt1000_norm_pos_loss1_wt035_pos_loss2_wt005_use_phase_use_patient_label1_v15/cl_feature_model.pt
  in_chns: 1
  val_epoch: 5
policy:
  policy_type: ranked
  seed: 1
  resume: True
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  seed: 1
  contrastive: True
  feature_model: True
  feature_model_params:
    cl_prev_path: /local2/amvepa91/al-seg1/LVMMED_sup_exp1_coreset_xt0_pos_loss1_wt033_pos_loss2_wt033_pos_loss3_wt033_use_slice_pos_use_phase_use_patient_v18/cl_feature_model.pt
    encoder: resnet18
    batch_size: 8
    seed: 1
    loss_wt: 0.0
    use_slice_pos: True
    use_phase: True
    use_patient: True
    pos_loss1: True
    pos_loss1_wt: .33
    pos_loss1_mask:
      - 2
      - 3
    pos_loss2: True
    pos_loss2_wt: .33
    pos_loss2_mask:
      - 3
    pos_loss3: True
    pos_loss3_wt: .33
    reset_sampler_every_epoch: True
exp_dir: "LVMMED_clf_sup_exp1_coreset_xt0_pos_loss1_wt033_pos_loss2_wt033_pos_loss3_wt033_use_slice_pos_use_phase_use_patient_v18"