model:
  model_type: "dmpls"
  ann_type: "scribble"
  ensemble_size: 5
  gpus: "cuda:0"
policy:
  policy_type: ranked
  seed: 1
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.04, 0], [.05, 0], [.05, 0], [.05, 0], [.20, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  seed: 1
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    fuse_image_data: True
    seed: 1
    use_slice_pos: True
    extra_loss: nt_xent_groups
    extra_loss_wt: 0.2
    reset_sampler_every_epoch: True
exp_dir: "DMPLS_exp1_coreset_fuse10_extra_loss_wt02_use_slice_pos_v7"