model:
  model_type: "strong"
  ann_type: "label"
  dataset: "DAVIS"
  ensemble_size: 5
  gpus: "cuda:0"
  inf_train_type: "features"
  in_chns: 3
policy:
  policy_type: ranked
  seed: 1
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.1, 0], [.1, 0], [.1, 0], [.1, 0]]
data_geometry:
  dataset_type: "DAVIS"
  data_geometry_type: kcenter_greedy
  seed: 1
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 9
    seed: 1
    use_slice_pos: True
    use_phase: True
    pos_loss1: True
    pos_loss1_wt: .3
    pos_loss1_mask:
      - 2
    pos_loss2: True
    pos_loss2_wt: .1
    reset_sampler_every_epoch: True
exp_dir: "DMPLS_sup_DAVIS_exp1_coreset_pos_loss1_wt03_pos_loss2_wt01_use_slice_pos_use_phase_v17"