model:
  model_type: "lvm_med"
  ann_type: "label"
  ensemble_size: 5
  gpus: "cuda:0"
  dataset: "DAVIS"
  in_chns: 3
  base_original_checkpoint: "imagenet_v2"
  val_epoch: 5
policy:
  policy_type: ranked
  seed: 0
  resume: True
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  dataset_type: "DAVIS"
  seed: 0
  contrastive: True
  feature_model: True
  feature_model_params:
    in_chns: 3
    encoder: resnet18
    batch_size: 8
    seed: 0
    loss_wt: 0.0
    use_slice_pos: False
    use_phase: True
    use_patient: False
    pos_loss1: True
    pos_loss1_wt: 1.0
    reset_sampler_every_epoch: True
exp_dir: "LVMMED_imagenet_sup_DAVIS_exp0_coreset_xt0_pos_loss1_wt1_use_phase_v19"