model:
  model_type: "lvm_med"
  ann_type: "label"
  ensemble_size: 5
  gpus: "cuda:0"
  dataset: "CHAOS_CT"
  base_original_checkpoint: "lvm-med-resnet"
  val_epoch: 5
policy:
  policy_type: ranked
  seed: 1
  resume: True
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  dataset_type: "CHAOS_CT"
  seed: 1
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    seed: 1
    loss_wt: 0.0
    use_slice_pos: False
    use_phase: False
    use_patient: True
    pos_loss1: True
    pos_loss1_wt: 1.0
    reset_sampler_every_epoch: True
exp_dir: "LVMMED_CHAOS_sup_exp1_coreset_xt0_pos_loss1_wt1_use_patient_v19"