model:
  model_type: "strong"
  ann_type: "label"
  dataset: "DAVIS"
  ensemble_size: 5
  gpus: "cuda:0"
  inf_train_type: "features"
  in_chns: 3
policy:
  policy_type: ranked
  seed: 3
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.1, 0], [.1, 0], [.1, 0], [.1, 0]]
data_geometry:
  dataset_type: "DAVIS"
  data_geometry_type: kcenter_greedy
  seed: 3
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    seed: 3
    use_phase: True
    pos_loss1: True
    pos_loss1_wt: .35
    reset_sampler_every_epoch: True
exp_dir: "DMPLS_sup_DAVIS_exp3_coreset_pos_loss1_wt035_use_phase_v17"