model:
  model_type: "strong"
  ann_type: "label"
  ensemble_size: 5
  gpus: "cuda:0"
policy:
  policy_type: ranked
  seed: 3
  resume: True
  ensemble_kwargs:
    skip: False
    inf_test: True
    inf_train: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0], [.05, 0], [.05, 0], [.05, 0], [.2, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  seed: 3
  contrastive: True
  feature_model: True
  extra_feature_wt: 1.0
  uncertainty_wt: 1.0
  use_uncertainty: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    fuse_image_data: True
    seed: 3
    use_slice_pos: True
    use_phase: True
    use_patient: True
    pos_loss1: True
    pos_loss1_wt: .2
    pos_loss1_mask:
      - 2
      - 3
    pos_loss2: True
    pos_loss2_wt: .1
    pos_loss2_mask:
      - 3
    pos_loss3: True
    pos_loss3_wt: .05
    reset_sampler_every_epoch: True
model_uncertainty:
  model_uncertainty_type: ensemble
  score_func: entropy_w_label_probs
exp_dir: "DMPLS_sup_exp3_coreset_fuse10_pos_loss1_wt02_pos_loss2_wt01_pos_loss3_wt005_use_slice_pos_use_phase_use_patient_uncertainty1_v11"