model:
  model_type: "dmpls"
  ann_type: "scribble"
  ensemble_size: 5
  gpus: "cuda:0"
policy:
  policy_type: ranked
  seed: 1
  resume: True
  ensemble_kwargs:
    skip: False
    inf_test: True
    inf_train: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  seed: 1
  contrastive: True
  feature_model: True
  extra_feature_wt: 1.0
  use_labels: True
  label_wt: 2.0
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    fuse_image_data: True
    fuse_image_data_size_prop: .2
    seed: 1
exp_dir: "DMPLS_exp1_coreset_fuse20_no_uncertainty_label2_v10"