model:
  model_type: "dmpls"
  ann_type: "scribble"
  ensemble_size: 5
  gpus: "cuda:0"
policy:
  policy_type: ranked
  seed: 0
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.04, 0], [.05, 0], [.05, 0], [.05, 0], [.20]]
data_geometry:
  data_geometry_type: kcenter_greedy
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
  seed: 0
exp_dir: "DMPLS_exp0_coreset_cl_bs8_v6"