model:
  model_type: "dmpls"
  ann_type: "scribble"
  ensemble_size: 5
  gpus: "cuda:0"
policy:
  policy_type: ranked
  seed: 1
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.04, 0], [.05, 0], [.05, 0], [.05, 0], [.20, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  seed: 1
  extra_feature_wt: 1.0
  slice_pos_wt: 20.0
  patient_wt: 20.0
  phase_wt: 20.0
  wt_max_dist_mult: .5
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    fuse_image_data: True
exp_dir: "DMPLS_exp1_coreset_slice_pos20_patient20_phase20_mult5_fuse10_fixed_v7"