model:
  model_type: "strong"
  ann_type: "label"
  ensemble_size: 3
  gpus: "cuda:0"
  in_chns: 3
  dataset: "DAVIS"
policy:
  policy_type: ranked
  seed: 0
  resume: True
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0, random, True], [.01, 0], [.01, 0], [.01, 0], [.01, 0], [.05, 0], [.05, 0], [.05, 0], [.20, 0]]
data_geometry:
  dataset_type: "DAVIS"
  data_geometry_type: typiclust
  knn_model: "sklearn"
  feature_model: True
  contrastive: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    num_epochs: 50
    in_chns: 3
    seed: 0
    reset_sampler_every_epoch: True
exp_dir: "DMPLS_sup_DAVIS_exp0_typiclust_v10"