model:
  model_type: "dmpls"
  ann_type: "scribble"
  dataset: "ACDC"
  ensemble_size: 5
  gpus: "cuda:0"
policy:
  policy_type: ranked
  resume: True
  seed: 4
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  seed: 4
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 9
    seed: 4
    loss_wt: 0.0
    use_phase: True
    use_patient: True
    pos_loss1: True
    pos_loss1_wt: .5
    pos_loss1_mask:
      - 2
    pos_loss2: True
    pos_loss2_wt: .5
    reset_sampler_every_epoch: True
model_uncertainty:
  model_uncertainty_type: ensemble
  score_func: entropy_w_label_probs
exp_dir: "DMPLS_exp4_coreset_xt0_pos_loss1_wt05_pos_loss2_wt05_use_phase_use_patient_v15"