model:
  model_type: "dmpls"
  ann_type: "scribble"
  dataset: "ACDC"
  ensemble_size: 5
  gpus: "cuda:0"
policy:
  policy_type: ranked
  seed: 3
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  seed: 3
  contrastive: True
  feature_model: True
  uncertainty_wt: 1.0
  use_uncertainty: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    fuse_image_data: True
    seed: 3
    use_phase: True
    pos_loss1: True
    pos_loss1_wt: .35
    reset_sampler_every_epoch: True
model_uncertainty:
  model_uncertainty_type: ensemble
  score_func: entropy_w_label_probs
exp_dir: "DMPLS_exp3_coreset_fuse10_pos_loss1_wt035_use_phase_uncertainty1_v15"