model:
  model_type: "dmpls"
  ann_type: "scribble"
  dataset: "ACDC"
  ensemble_size: 1
  gpus: "cuda:0"
  inf_train_type: "preds"
policy:
  policy_type: ranked
  resume: True
  seed: 0
  ensemble_kwargs:
    skip: False
    inf_test: True
    inf_train: True
  rounds: [[.001, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  seed: 0
  delete_preds: False
  contrastive: True
  feature_model: True
  pos_wt: 10
  default_pos_val: 0
  use_labels: True
  use_model_fts_as_pos_fts: True
  label_wt: 1.0
  normalize_pos_by_label_ct: True
  feature_model_params:
    encoder: resnet18
    batch_size: 9
    seed: 0
    use_phase: True
    use_patient: True
    pos_loss1: True
    pos_loss1_wt: .35
    pos_loss1_mask:
      - 2
    pos_loss2: True
    pos_loss2_wt: .05
    reset_sampler_every_epoch: True
model_uncertainty:
  model_uncertainty_type: ensemble
  score_func: entropy_w_label_probs
exp_dir: "DMPLS_exp_new_test"