model:
  model_type: "dmpls"
  ann_type: "scribble"
  dataset: "ACDC"
  ensemble_size: 1
  gpus: "cuda:0"
policy:
  policy_type: ranked
  resume: True
  seed: 0
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.001, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  seed: 0
  contrastive: True
  feature_model: True
  pos_wt: 1500
  default_pos_val: 0
  use_labels: True
  label_wt: 1.0
  uncertainty_wt: 5
  use_uncertainty: True
  normalize_pos_by_label_ct: True
  feature_model_params:
    encoder: resnet18
    batch_size: 9
    seed: 0
    fuse_image_data: True
    fuse_image_data_size_prop: .10
    use_phase: True
    use_patient: True
    pos_loss1: True
    pos_loss1_wt: .35
    pos_loss1_mask:
      - 2
    pos_loss2: True
    pos_loss2_wt: .05
    reset_sampler_every_epoch: True
model_uncertainty:
  model_uncertainty_type: ensemble
  score_func: ensemble_variance_ratio
exp_dir: "DMPLS_exp0_coreset_pos_wt1500_norm_pos_loss1_wt035_pos_loss2_wt005_use_phase_use_patient_label1_var5_v15"