model:
  model_type: "db_strong"
  ann_type: "label"
  dataset: "CHAOS_CT"
  ensemble_size: 5
  gpus: "cuda:0"
  inf_train_type: "features"
policy:
  policy_type: ranked
  seed: 2
  ensemble_kwargs:
    skip: False
    inf_test: True
  rounds: [[.01, 0], [.01, 0], [.01, 0], [.01, 0], [.01, 0], [0.05, 0], [0.05, 0], [0.05, 0], [0.2, 0]]
data_geometry:
  dataset_type: "CHAOS_CT"
  data_geometry_type: kcenter_greedy
  seed: 2
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 9
    seed: 2
    use_slice_pos: True
    use_phase: True
    pos_loss1: True
    pos_loss1_wt: .3
    pos_loss1_mask:
      - 2
    pos_loss2: True
    pos_loss2_wt: .1
    reset_sampler_every_epoch: True
exp_dir: "DMPLS_sup_CHAOS_exp2_coreset_pos_loss1_wt03_pos_loss2_wt01_use_slice_pos_use_phase_v17"