model:
  model_type: "dmpls"
  ann_type: "scribble"
  ensemble_size: 1
  gpus: "mps"
  inf_train_type: "features"
policy:
  policy_type: ranked
  seed: 0
  ensemble_kwargs:
    skip: False
    inf_test: False
  rounds: [[.005, 0], [.005, 0], [.005, 0]]
data_geometry:
  data_geometry_type: contrastive
  batch_size: 8
  gpus: "mps"
exp_dir: "DMPLS_w_contrast_mdl_ft_test_run"