model:
  model_type: "dmpls"
  ann_type: "scribble"
  dataset: "MSCMR"
  ensemble_size: 1
  max_iterations: 30000
  gpus: "cuda:0"
policy:
  policy_type: ranked
  seed: 0
  ensemble_kwargs:
    skip: False
    inf_test: False
  rounds: [[.1, 0], [.05, 0], [.05, 0], [.05, 0], [.05, 0]]
data_geometry:
  dataset_type: "MSCMR"
  data_geometry_type: kcenter_greedy
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    patience: 1
    num_epochs: 5
    debug: True
    fuse_image_data: True
    use_patient: True
    use_slice_pos: True
    use_phase: True
    neg_loss: True
    neg_loss_wt: 0.8
    pos_loss1: True
    pos_loss1_wt: .2
    pos_loss1_mask:
      - 2
      - 3
    pos_loss2: True
    pos_loss2_wt: .2
    pos_loss2_mask:
      - 3
    pos_loss3: True
    pos_loss3_wt: .2
    loss_wt: 0.2
    reset_sampler_every_epoch: True
exp_dir: "DMPLS_MSCMR_coreset_cl_test_run"