model:
  model_type: "dmpls"
  ann_type: "scribble"
  ensemble_size: 1
  gpus: "cuda:0"
policy:
  policy_type: ranked
  seed: 0
  ensemble_kwargs:
    skip: False
    inf_test: False
  rounds: [[.005, 0, random, True], [.005, 0], [.005, 0]]
data_geometry:
  data_geometry_type: kcenter_greedy
  contrastive: True
  feature_model: True
  feature_model_params:
    encoder: resnet18
    batch_size: 8
    patience: 1
    num_epochs: 5
    debug: True
    fuse_image_data: True
    use_patient: True
    use_slice_pos: True
    use_phase: True
    extra_loss: nt_xent_groups
    extra_loss_wt: 0.8
    loss_wt: 0.2
    reset_sampler_every_epoch: True
exp_dir: "DMPLS_w_coreset_cl_test_run"